// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HardwareInformationMessages.proto

package Network.DataModel;

public final class HardwareInformationMessages {
  private HardwareInformationMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code HardwareRequestTypes}
   */
  public enum HardwareRequestTypes
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>XML = 0;</code>
     */
    XML(0),
    /**
     * <code>JSON = 1;</code>
     */
    JSON(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>XML = 0;</code>
     */
    public static final int XML_VALUE = 0;
    /**
     * <code>JSON = 1;</code>
     */
    public static final int JSON_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HardwareRequestTypes valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HardwareRequestTypes forNumber(int value) {
      switch (value) {
        case 0: return XML;
        case 1: return JSON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HardwareRequestTypes>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HardwareRequestTypes> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HardwareRequestTypes>() {
            public HardwareRequestTypes findValueByNumber(int number) {
              return HardwareRequestTypes.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Network.DataModel.HardwareInformationMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final HardwareRequestTypes[] VALUES = values();

    public static HardwareRequestTypes valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HardwareRequestTypes(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HardwareRequestTypes)
  }

  public interface HardwareInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HardwareInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hardwareDescription = 1;</code>
     * @return The hardwareDescription.
     */
    java.lang.String getHardwareDescription();
    /**
     * <code>string hardwareDescription = 1;</code>
     * @return The bytes for hardwareDescription.
     */
    com.google.protobuf.ByteString
        getHardwareDescriptionBytes();
  }
  /**
   * Protobuf type {@code HardwareInformation}
   */
  public static final class HardwareInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HardwareInformation)
      HardwareInformationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HardwareInformation.newBuilder() to construct.
    private HardwareInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HardwareInformation() {
      hardwareDescription_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HardwareInformation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Network.DataModel.HardwareInformationMessages.HardwareInformation.class, Network.DataModel.HardwareInformationMessages.HardwareInformation.Builder.class);
    }

    public static final int HARDWAREDESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object hardwareDescription_;
    /**
     * <code>string hardwareDescription = 1;</code>
     * @return The hardwareDescription.
     */
    @java.lang.Override
    public java.lang.String getHardwareDescription() {
      java.lang.Object ref = hardwareDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hardwareDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string hardwareDescription = 1;</code>
     * @return The bytes for hardwareDescription.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHardwareDescriptionBytes() {
      java.lang.Object ref = hardwareDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hardwareDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hardwareDescription_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hardwareDescription_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hardwareDescription_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hardwareDescription_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Network.DataModel.HardwareInformationMessages.HardwareInformation)) {
        return super.equals(obj);
      }
      Network.DataModel.HardwareInformationMessages.HardwareInformation other = (Network.DataModel.HardwareInformationMessages.HardwareInformation) obj;

      if (!getHardwareDescription()
          .equals(other.getHardwareDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HARDWAREDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getHardwareDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Network.DataModel.HardwareInformationMessages.HardwareInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HardwareInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HardwareInformation)
        Network.DataModel.HardwareInformationMessages.HardwareInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Network.DataModel.HardwareInformationMessages.HardwareInformation.class, Network.DataModel.HardwareInformationMessages.HardwareInformation.Builder.class);
      }

      // Construct using Network.DataModel.HardwareInformationMessages.HardwareInformation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hardwareDescription_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformation_descriptor;
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformation getDefaultInstanceForType() {
        return Network.DataModel.HardwareInformationMessages.HardwareInformation.getDefaultInstance();
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformation build() {
        Network.DataModel.HardwareInformationMessages.HardwareInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformation buildPartial() {
        Network.DataModel.HardwareInformationMessages.HardwareInformation result = new Network.DataModel.HardwareInformationMessages.HardwareInformation(this);
        result.hardwareDescription_ = hardwareDescription_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Network.DataModel.HardwareInformationMessages.HardwareInformation) {
          return mergeFrom((Network.DataModel.HardwareInformationMessages.HardwareInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Network.DataModel.HardwareInformationMessages.HardwareInformation other) {
        if (other == Network.DataModel.HardwareInformationMessages.HardwareInformation.getDefaultInstance()) return this;
        if (!other.getHardwareDescription().isEmpty()) {
          hardwareDescription_ = other.hardwareDescription_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                hardwareDescription_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object hardwareDescription_ = "";
      /**
       * <code>string hardwareDescription = 1;</code>
       * @return The hardwareDescription.
       */
      public java.lang.String getHardwareDescription() {
        java.lang.Object ref = hardwareDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hardwareDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hardwareDescription = 1;</code>
       * @return The bytes for hardwareDescription.
       */
      public com.google.protobuf.ByteString
          getHardwareDescriptionBytes() {
        java.lang.Object ref = hardwareDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hardwareDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hardwareDescription = 1;</code>
       * @param value The hardwareDescription to set.
       * @return This builder for chaining.
       */
      public Builder setHardwareDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hardwareDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hardwareDescription = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHardwareDescription() {
        
        hardwareDescription_ = getDefaultInstance().getHardwareDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string hardwareDescription = 1;</code>
       * @param value The bytes for hardwareDescription to set.
       * @return This builder for chaining.
       */
      public Builder setHardwareDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hardwareDescription_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HardwareInformation)
    }

    // @@protoc_insertion_point(class_scope:HardwareInformation)
    private static final Network.DataModel.HardwareInformationMessages.HardwareInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Network.DataModel.HardwareInformationMessages.HardwareInformation();
    }

    public static Network.DataModel.HardwareInformationMessages.HardwareInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HardwareInformation>
        PARSER = new com.google.protobuf.AbstractParser<HardwareInformation>() {
      @java.lang.Override
      public HardwareInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HardwareInformation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HardwareInformation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Network.DataModel.HardwareInformationMessages.HardwareInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HardwareInformationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HardwareInformationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 targetPort = 1;</code>
     * @return The targetPort.
     */
    int getTargetPort();

    /**
     * <code>.HardwareRequestTypes type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.HardwareRequestTypes type = 2;</code>
     * @return The type.
     */
    Network.DataModel.HardwareInformationMessages.HardwareRequestTypes getType();
  }
  /**
   * Protobuf type {@code HardwareInformationRequest}
   */
  public static final class HardwareInformationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HardwareInformationRequest)
      HardwareInformationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HardwareInformationRequest.newBuilder() to construct.
    private HardwareInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HardwareInformationRequest() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HardwareInformationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.class, Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.Builder.class);
    }

    public static final int TARGETPORT_FIELD_NUMBER = 1;
    private int targetPort_;
    /**
     * <code>int32 targetPort = 1;</code>
     * @return The targetPort.
     */
    @java.lang.Override
    public int getTargetPort() {
      return targetPort_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.HardwareRequestTypes type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.HardwareRequestTypes type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public Network.DataModel.HardwareInformationMessages.HardwareRequestTypes getType() {
      @SuppressWarnings("deprecation")
      Network.DataModel.HardwareInformationMessages.HardwareRequestTypes result = Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.valueOf(type_);
      return result == null ? Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (targetPort_ != 0) {
        output.writeInt32(1, targetPort_);
      }
      if (type_ != Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.XML.getNumber()) {
        output.writeEnum(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (targetPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, targetPort_);
      }
      if (type_ != Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.XML.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Network.DataModel.HardwareInformationMessages.HardwareInformationRequest)) {
        return super.equals(obj);
      }
      Network.DataModel.HardwareInformationMessages.HardwareInformationRequest other = (Network.DataModel.HardwareInformationMessages.HardwareInformationRequest) obj;

      if (getTargetPort()
          != other.getTargetPort()) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGETPORT_FIELD_NUMBER;
      hash = (53 * hash) + getTargetPort();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Network.DataModel.HardwareInformationMessages.HardwareInformationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HardwareInformationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HardwareInformationRequest)
        Network.DataModel.HardwareInformationMessages.HardwareInformationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.class, Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.Builder.class);
      }

      // Construct using Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        targetPort_ = 0;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Network.DataModel.HardwareInformationMessages.internal_static_HardwareInformationRequest_descriptor;
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformationRequest getDefaultInstanceForType() {
        return Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformationRequest build() {
        Network.DataModel.HardwareInformationMessages.HardwareInformationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareInformationRequest buildPartial() {
        Network.DataModel.HardwareInformationMessages.HardwareInformationRequest result = new Network.DataModel.HardwareInformationMessages.HardwareInformationRequest(this);
        result.targetPort_ = targetPort_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Network.DataModel.HardwareInformationMessages.HardwareInformationRequest) {
          return mergeFrom((Network.DataModel.HardwareInformationMessages.HardwareInformationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Network.DataModel.HardwareInformationMessages.HardwareInformationRequest other) {
        if (other == Network.DataModel.HardwareInformationMessages.HardwareInformationRequest.getDefaultInstance()) return this;
        if (other.getTargetPort() != 0) {
          setTargetPort(other.getTargetPort());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                targetPort_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                type_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int targetPort_ ;
      /**
       * <code>int32 targetPort = 1;</code>
       * @return The targetPort.
       */
      @java.lang.Override
      public int getTargetPort() {
        return targetPort_;
      }
      /**
       * <code>int32 targetPort = 1;</code>
       * @param value The targetPort to set.
       * @return This builder for chaining.
       */
      public Builder setTargetPort(int value) {
        
        targetPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 targetPort = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetPort() {
        
        targetPort_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.HardwareRequestTypes type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.HardwareRequestTypes type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.HardwareRequestTypes type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public Network.DataModel.HardwareInformationMessages.HardwareRequestTypes getType() {
        @SuppressWarnings("deprecation")
        Network.DataModel.HardwareInformationMessages.HardwareRequestTypes result = Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.valueOf(type_);
        return result == null ? Network.DataModel.HardwareInformationMessages.HardwareRequestTypes.UNRECOGNIZED : result;
      }
      /**
       * <code>.HardwareRequestTypes type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(Network.DataModel.HardwareInformationMessages.HardwareRequestTypes value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.HardwareRequestTypes type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HardwareInformationRequest)
    }

    // @@protoc_insertion_point(class_scope:HardwareInformationRequest)
    private static final Network.DataModel.HardwareInformationMessages.HardwareInformationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Network.DataModel.HardwareInformationMessages.HardwareInformationRequest();
    }

    public static Network.DataModel.HardwareInformationMessages.HardwareInformationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HardwareInformationRequest>
        PARSER = new com.google.protobuf.AbstractParser<HardwareInformationRequest>() {
      @java.lang.Override
      public HardwareInformationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HardwareInformationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HardwareInformationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Network.DataModel.HardwareInformationMessages.HardwareInformationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HardwareInformation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HardwareInformation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HardwareInformationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HardwareInformationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!HardwareInformationMessages.proto\"2\n\023H" +
      "ardwareInformation\022\033\n\023hardwareDescriptio" +
      "n\030\001 \001(\t\"U\n\032HardwareInformationRequest\022\022\n" +
      "\ntargetPort\030\001 \001(\005\022#\n\004type\030\002 \001(\0162\025.Hardwa" +
      "reRequestTypes*)\n\024HardwareRequestTypes\022\007" +
      "\n\003XML\020\000\022\010\n\004JSON\020\001B\023\n\021Network.DataModelb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HardwareInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HardwareInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HardwareInformation_descriptor,
        new java.lang.String[] { "HardwareDescription", });
    internal_static_HardwareInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HardwareInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HardwareInformationRequest_descriptor,
        new java.lang.String[] { "TargetPort", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
